---
- import_tasks: kolla_prepare_online.yml
  when: inventory_hostname in groups['kolla_prepare_online']
  tags:
    - prepare_online

- import_tasks: kolla_prepare_offline.yml
  when: inventory_hostname in groups['kolla_prepare_offline']
  tags:
    - prepare_offline

- import_tasks: kolla_deploy.yml
  when: "'kolla_deploy' in group_names"
  tags:
    - deploy
